apiVersion: v1
kind: Secret
metadata:
  name: {{ include "galene.secretName" . }}
  labels:
    {{- include "galene.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: "{{ .Values.secrets.username }}"
  password: "{{ .Values.secrets.password }}"
